### ISSUE TITLE
Text stirng

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/mesud-karakayali-onboardscreen-login#1]
Buradaki textleri ya sayfa basında tanımlayacağız ya da stirng classndan çekmeliyiz
https://github.com/VBT-FlutterCamp/mesud-karakayali-onboardscreen/blob/3e7543f66d2a2bdf9ebbfcf053c6e63889dc519c/lib/products/widgets/custom_text_form_field.dart#L46

**Comment by mesud07** [comment]
TextFormFieldStrings içerisinde tanımlandı
