### ISSUE TITLE
Kontrol

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/mesud-karakayali-onboardscreen-login#2]
Buradki kontorlü sayfa içerinde kontrol etmemlitiz. Dısarıdan bir fonksiyon ile farklı bir sınıftan çekmeliyiz.
https://github.com/VBT-FlutterCamp/mesud-karakayali-onboardscreen/blob/3e7543f66d2a2bdf9ebbfcf053c6e63889dc519c/lib/feature/splash/view/splash_view.dart#L88

**Comment by mesud07** [comment]
fonksiyona çevrildi
