### ISSUE TITLE
Methodlaştırma

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/mesud-karakayali-onboardscreen-login#3]
Sayfa içerisndeki containerleı methodlaştıalım
https://github.com/VBT-FlutterCamp/mesud-karakayali-onboardscreen/blob/3e7543f66d2a2bdf9ebbfcf053c6e63889dc519c/lib/feature/onboard/view/onboard_view.dart#L42

**Comment by mesud07** [comment]
Column methodlaştırıldı
