### ISSUE TITLE
Paket

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/mesud-karakayali-onboardscreen-login#4]
Paketleri projede komplek bir yapı olmadıgı için hangi amaçla kullanmak istedik
https://github.com/VBT-FlutterCamp/mesud-karakayali-onboardscreen/blob/3e7543f66d2a2bdf9ebbfcf053c6e63889dc519c/pubspec.yaml#L40

**Comment by mesud07** [comment]
bir şeyi denemek için eklemiştim unutmuşum 
Silindi.
